// Copyright 2014-present 650 Industries. All rights reserved.

#import "NativeSources.h"


// EmbeddedNativeSources.m is autogenerated
@interface EmbeddedNativeSources : NSObject <NativeSourcesProtocol>

+ (instancetype)sharedSources;

@end
